title: Beining Zhang
<<<<<<< HEAD
Logo: /img/BeiningZhang.JPG
=======
Logo: /assets:img/BeiningZhang.JPG
>>>>>>> 0057180b5b93fafe1820f4e1a2c3184154edb030
#description: use this if you want to overwrite your repo description
# show_downloads: true 
theme: jekyll-theme-minimal
