title: Beining Zhang
logo: /assets/img/portfolio_photo.png
description: Experienced Data Scientist with 3+ years of experience in the financial industry, specialising in data analytics and machine learning.
#show_downloads: true
theme: jekyll-theme-minimal
