title: Beining Zhang
logo: /assets/img/portfolio_photo.png
description: [Resume](https://beiningzhang.github.io/resume)[Projects](https://beiningzhang.github.io/project)
#show_downloads: true
theme: jekyll-theme-minimal
