title: Beining Zhang
logo: /assets/img/portfolio_photo.png
description: [![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/beining-zhang)
#show_downloads: true
theme: jekyll-theme-minimal
